# .github/workflows/build.yml
name: build-exe
on: [push]
jobs:
  win-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: "3.11" }
    - run: pip install -U pip ccxt pandas numpy pyyaml pyinstaller
    - run: pyinstaller --onefile --noconsole --add-data "config.yaml;." bot.py
    - uses: actions/upload-artifact@v4
      with:
        name: bot-exe
        path: dist/bot.exe
